server:
  port: 8082
spring:
  application:
    name: menu-service
  datasource:
    password: culinarycode
    url: jdbc:postgresql://menu-service-db:5432/menu
    username: culinarycode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
